
osx_image: xcode7.2
language: objective-c
xcode_project: MultidirectionalScroll.xcodeproj
xcode_scheme: MultidirectionalScrollTests

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec