
osx_image: xcode7.2
language: objective-c 
script:  
   - xctool -project MultidirectionalScroll.xcodeproj -scheme MultidirectionalScrollTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec